### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by GloireIrenge** [melashu/MDS#2]
Congratulations, you made a great job but you still have some changes to make:
- Please respect the indentation in your HTML codes to make it readable.
- To avoid the text-overflow in your program section, please reduce the title's font-size

**Comment by melashu** [comment]
> Congratulations, you made a great job but you still have some changes to make:
> 
> * Please respect the indentation in your HTML codes to make it readable.
> * To avoid the text-overflow in your program section, please reduce the title's font-size

Hi @GloireIrenge 
I really appreciate your feedback. Thank you so much!
